apiVersion: apps/v1
kind: Deployment
metadata:
  name: cfml-qoq-sample-deployment-cf2018
spec:
  selector:
    matchLabels:
      app: cfml-qoq-sample-cf2018
  replicas: 1 
  template:
    metadata:
      labels:
        app: cfml-qoq-sample-cf2018
    spec:
      containers:
      - name: cfml-qoq-sample-cf2018
        image: registry.gitlab.com/kukielp/cfml:samplecb
        ports:
        - containerPort: 8080
        env:
          - name: CFENGINE
            value: adobe@2018
          - name: UN_DATABASE
            value: "postgres"
          - name: PW_DATABASE
            value: "Test123#"
          - name: DNS_DATABASE
            value: "postgres.kukiel.local"
          - name: NAME_DATABASE
            value: "sample"
        imagePullPolicy: Always
      hostAliases:
        - ip: "192.168.1.220"
          hostnames:
          - "postgres.kukiel.local"
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: cfml-qoq-sample-cf2018
spec:
  ports:
    - name: client
      protocol: TCP
      port: 80
      targetPort: 8080   
  selector:
    app: cfml-qoq-sample-cf2018
  type: LoadBalancer