version: '3'
services:
  postgres:
    image: postgres:latest
    ports: 
      - "5432:5432"
    container_name: database
    environment:
      - POSTGRES_PASSWORD=password
  lucee:
    image: lucee/lucee:5.3-nginx
    depends_on:
      - postgres
    environment:
      - DNS_DATABASE=database
      - NAME_DATABASE=postgres
      - UN_DATABASE=postgres
      - PW_DATABASE=password
    volumes:
      - ./www:/var/www
    ports: 
      - "8852:8888"
      - "8052:80"